// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: atsapbx/v1/identity.proto

package atsapbxv1connect

import (
	v1 "atsap-api/internal/genproto/atsapbx/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IdentityServiceName is the fully-qualified name of the IdentityService service.
	IdentityServiceName = "atsapbx.v1.IdentityService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IdentityServiceAuthenticateUserProcedure is the fully-qualified name of the IdentityService's
	// AuthenticateUser RPC.
	IdentityServiceAuthenticateUserProcedure = "/atsapbx.v1.IdentityService/AuthenticateUser"
	// IdentityServiceProvisionTenantProcedure is the fully-qualified name of the IdentityService's
	// ProvisionTenant RPC.
	IdentityServiceProvisionTenantProcedure = "/atsapbx.v1.IdentityService/ProvisionTenant"
	// IdentityServiceProvisionPrincipalProcedure is the fully-qualified name of the IdentityService's
	// ProvisionPrincipal RPC.
	IdentityServiceProvisionPrincipalProcedure = "/atsapbx.v1.IdentityService/ProvisionPrincipal"
	// IdentityServiceSetTenantStatusProcedure is the fully-qualified name of the IdentityService's
	// SetTenantStatus RPC.
	IdentityServiceSetTenantStatusProcedure = "/atsapbx.v1.IdentityService/SetTenantStatus"
	// IdentityServiceSetPrincipalStatusProcedure is the fully-qualified name of the IdentityService's
	// SetPrincipalStatus RPC.
	IdentityServiceSetPrincipalStatusProcedure = "/atsapbx.v1.IdentityService/SetPrincipalStatus"
	// IdentityServiceGrantRoleProcedure is the fully-qualified name of the IdentityService's GrantRole
	// RPC.
	IdentityServiceGrantRoleProcedure = "/atsapbx.v1.IdentityService/GrantRole"
	// IdentityServiceIssueApiKeyProcedure is the fully-qualified name of the IdentityService's
	// IssueApiKey RPC.
	IdentityServiceIssueApiKeyProcedure = "/atsapbx.v1.IdentityService/IssueApiKey"
	// IdentityServiceRevokeApiKeyProcedure is the fully-qualified name of the IdentityService's
	// RevokeApiKey RPC.
	IdentityServiceRevokeApiKeyProcedure = "/atsapbx.v1.IdentityService/RevokeApiKey"
	// IdentityServiceListAuditProcedure is the fully-qualified name of the IdentityService's ListAudit
	// RPC.
	IdentityServiceListAuditProcedure = "/atsapbx.v1.IdentityService/ListAudit"
)

// IdentityServiceClient is a client for the atsapbx.v1.IdentityService service.
type IdentityServiceClient interface {
	// AuthenticateUser exchanges a username and password for a
	// short-lived token. The only method reachable without one.
	AuthenticateUser(context.Context, *connect.Request[v1.AuthenticateUserRequest]) (*connect.Response[v1.AuthenticateUserResponse], error)
	// ProvisionTenant creates a tenant. Its residency zone is fixed here
	// and cannot be changed afterwards.
	ProvisionTenant(context.Context, *connect.Request[v1.ProvisionTenantRequest]) (*connect.Response[v1.ProvisionTenantResponse], error)
	// ProvisionPrincipal creates a user account within a tenant.
	ProvisionPrincipal(context.Context, *connect.Request[v1.ProvisionPrincipalRequest]) (*connect.Response[v1.ProvisionPrincipalResponse], error)
	// SetTenantStatus suspends or reactivates a tenant. Reversible, and it
	// never terminates a call already in progress (INV-03).
	SetTenantStatus(context.Context, *connect.Request[v1.SetTenantStatusRequest]) (*connect.Response[v1.SetTenantStatusResponse], error)
	// SetPrincipalStatus disables or reactivates an account. Takes effect
	// on that account's next request, not at token expiry.
	SetPrincipalStatus(context.Context, *connect.Request[v1.SetPrincipalStatusRequest]) (*connect.Response[v1.SetPrincipalStatusResponse], error)
	// GrantRole binds a role to a principal within a scope.
	GrantRole(context.Context, *connect.Request[v1.GrantRoleRequest]) (*connect.Response[v1.GrantRoleResponse], error)
	// IssueApiKey creates a machine credential. Its response is the only
	// place the usable key value ever appears.
	IssueApiKey(context.Context, *connect.Request[v1.IssueApiKeyRequest]) (*connect.Response[v1.IssueApiKeyResponse], error)
	// RevokeApiKey makes a key unusable immediately.
	RevokeApiKey(context.Context, *connect.Request[v1.RevokeApiKeyRequest]) (*connect.Response[v1.RevokeApiKeyResponse], error)
	// ListAudit returns the calling tenant's most recent audit records.
	ListAudit(context.Context, *connect.Request[v1.ListAuditRequest]) (*connect.Response[v1.ListAuditResponse], error)
}

// NewIdentityServiceClient constructs a client for the atsapbx.v1.IdentityService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIdentityServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IdentityServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	identityServiceMethods := v1.File_atsapbx_v1_identity_proto.Services().ByName("IdentityService").Methods()
	return &identityServiceClient{
		authenticateUser: connect.NewClient[v1.AuthenticateUserRequest, v1.AuthenticateUserResponse](
			httpClient,
			baseURL+IdentityServiceAuthenticateUserProcedure,
			connect.WithSchema(identityServiceMethods.ByName("AuthenticateUser")),
			connect.WithClientOptions(opts...),
		),
		provisionTenant: connect.NewClient[v1.ProvisionTenantRequest, v1.ProvisionTenantResponse](
			httpClient,
			baseURL+IdentityServiceProvisionTenantProcedure,
			connect.WithSchema(identityServiceMethods.ByName("ProvisionTenant")),
			connect.WithClientOptions(opts...),
		),
		provisionPrincipal: connect.NewClient[v1.ProvisionPrincipalRequest, v1.ProvisionPrincipalResponse](
			httpClient,
			baseURL+IdentityServiceProvisionPrincipalProcedure,
			connect.WithSchema(identityServiceMethods.ByName("ProvisionPrincipal")),
			connect.WithClientOptions(opts...),
		),
		setTenantStatus: connect.NewClient[v1.SetTenantStatusRequest, v1.SetTenantStatusResponse](
			httpClient,
			baseURL+IdentityServiceSetTenantStatusProcedure,
			connect.WithSchema(identityServiceMethods.ByName("SetTenantStatus")),
			connect.WithClientOptions(opts...),
		),
		setPrincipalStatus: connect.NewClient[v1.SetPrincipalStatusRequest, v1.SetPrincipalStatusResponse](
			httpClient,
			baseURL+IdentityServiceSetPrincipalStatusProcedure,
			connect.WithSchema(identityServiceMethods.ByName("SetPrincipalStatus")),
			connect.WithClientOptions(opts...),
		),
		grantRole: connect.NewClient[v1.GrantRoleRequest, v1.GrantRoleResponse](
			httpClient,
			baseURL+IdentityServiceGrantRoleProcedure,
			connect.WithSchema(identityServiceMethods.ByName("GrantRole")),
			connect.WithClientOptions(opts...),
		),
		issueApiKey: connect.NewClient[v1.IssueApiKeyRequest, v1.IssueApiKeyResponse](
			httpClient,
			baseURL+IdentityServiceIssueApiKeyProcedure,
			connect.WithSchema(identityServiceMethods.ByName("IssueApiKey")),
			connect.WithClientOptions(opts...),
		),
		revokeApiKey: connect.NewClient[v1.RevokeApiKeyRequest, v1.RevokeApiKeyResponse](
			httpClient,
			baseURL+IdentityServiceRevokeApiKeyProcedure,
			connect.WithSchema(identityServiceMethods.ByName("RevokeApiKey")),
			connect.WithClientOptions(opts...),
		),
		listAudit: connect.NewClient[v1.ListAuditRequest, v1.ListAuditResponse](
			httpClient,
			baseURL+IdentityServiceListAuditProcedure,
			connect.WithSchema(identityServiceMethods.ByName("ListAudit")),
			connect.WithClientOptions(opts...),
		),
	}
}

// identityServiceClient implements IdentityServiceClient.
type identityServiceClient struct {
	authenticateUser   *connect.Client[v1.AuthenticateUserRequest, v1.AuthenticateUserResponse]
	provisionTenant    *connect.Client[v1.ProvisionTenantRequest, v1.ProvisionTenantResponse]
	provisionPrincipal *connect.Client[v1.ProvisionPrincipalRequest, v1.ProvisionPrincipalResponse]
	setTenantStatus    *connect.Client[v1.SetTenantStatusRequest, v1.SetTenantStatusResponse]
	setPrincipalStatus *connect.Client[v1.SetPrincipalStatusRequest, v1.SetPrincipalStatusResponse]
	grantRole          *connect.Client[v1.GrantRoleRequest, v1.GrantRoleResponse]
	issueApiKey        *connect.Client[v1.IssueApiKeyRequest, v1.IssueApiKeyResponse]
	revokeApiKey       *connect.Client[v1.RevokeApiKeyRequest, v1.RevokeApiKeyResponse]
	listAudit          *connect.Client[v1.ListAuditRequest, v1.ListAuditResponse]
}

// AuthenticateUser calls atsapbx.v1.IdentityService.AuthenticateUser.
func (c *identityServiceClient) AuthenticateUser(ctx context.Context, req *connect.Request[v1.AuthenticateUserRequest]) (*connect.Response[v1.AuthenticateUserResponse], error) {
	return c.authenticateUser.CallUnary(ctx, req)
}

// ProvisionTenant calls atsapbx.v1.IdentityService.ProvisionTenant.
func (c *identityServiceClient) ProvisionTenant(ctx context.Context, req *connect.Request[v1.ProvisionTenantRequest]) (*connect.Response[v1.ProvisionTenantResponse], error) {
	return c.provisionTenant.CallUnary(ctx, req)
}

// ProvisionPrincipal calls atsapbx.v1.IdentityService.ProvisionPrincipal.
func (c *identityServiceClient) ProvisionPrincipal(ctx context.Context, req *connect.Request[v1.ProvisionPrincipalRequest]) (*connect.Response[v1.ProvisionPrincipalResponse], error) {
	return c.provisionPrincipal.CallUnary(ctx, req)
}

// SetTenantStatus calls atsapbx.v1.IdentityService.SetTenantStatus.
func (c *identityServiceClient) SetTenantStatus(ctx context.Context, req *connect.Request[v1.SetTenantStatusRequest]) (*connect.Response[v1.SetTenantStatusResponse], error) {
	return c.setTenantStatus.CallUnary(ctx, req)
}

// SetPrincipalStatus calls atsapbx.v1.IdentityService.SetPrincipalStatus.
func (c *identityServiceClient) SetPrincipalStatus(ctx context.Context, req *connect.Request[v1.SetPrincipalStatusRequest]) (*connect.Response[v1.SetPrincipalStatusResponse], error) {
	return c.setPrincipalStatus.CallUnary(ctx, req)
}

// GrantRole calls atsapbx.v1.IdentityService.GrantRole.
func (c *identityServiceClient) GrantRole(ctx context.Context, req *connect.Request[v1.GrantRoleRequest]) (*connect.Response[v1.GrantRoleResponse], error) {
	return c.grantRole.CallUnary(ctx, req)
}

// IssueApiKey calls atsapbx.v1.IdentityService.IssueApiKey.
func (c *identityServiceClient) IssueApiKey(ctx context.Context, req *connect.Request[v1.IssueApiKeyRequest]) (*connect.Response[v1.IssueApiKeyResponse], error) {
	return c.issueApiKey.CallUnary(ctx, req)
}

// RevokeApiKey calls atsapbx.v1.IdentityService.RevokeApiKey.
func (c *identityServiceClient) RevokeApiKey(ctx context.Context, req *connect.Request[v1.RevokeApiKeyRequest]) (*connect.Response[v1.RevokeApiKeyResponse], error) {
	return c.revokeApiKey.CallUnary(ctx, req)
}

// ListAudit calls atsapbx.v1.IdentityService.ListAudit.
func (c *identityServiceClient) ListAudit(ctx context.Context, req *connect.Request[v1.ListAuditRequest]) (*connect.Response[v1.ListAuditResponse], error) {
	return c.listAudit.CallUnary(ctx, req)
}

// IdentityServiceHandler is an implementation of the atsapbx.v1.IdentityService service.
type IdentityServiceHandler interface {
	// AuthenticateUser exchanges a username and password for a
	// short-lived token. The only method reachable without one.
	AuthenticateUser(context.Context, *connect.Request[v1.AuthenticateUserRequest]) (*connect.Response[v1.AuthenticateUserResponse], error)
	// ProvisionTenant creates a tenant. Its residency zone is fixed here
	// and cannot be changed afterwards.
	ProvisionTenant(context.Context, *connect.Request[v1.ProvisionTenantRequest]) (*connect.Response[v1.ProvisionTenantResponse], error)
	// ProvisionPrincipal creates a user account within a tenant.
	ProvisionPrincipal(context.Context, *connect.Request[v1.ProvisionPrincipalRequest]) (*connect.Response[v1.ProvisionPrincipalResponse], error)
	// SetTenantStatus suspends or reactivates a tenant. Reversible, and it
	// never terminates a call already in progress (INV-03).
	SetTenantStatus(context.Context, *connect.Request[v1.SetTenantStatusRequest]) (*connect.Response[v1.SetTenantStatusResponse], error)
	// SetPrincipalStatus disables or reactivates an account. Takes effect
	// on that account's next request, not at token expiry.
	SetPrincipalStatus(context.Context, *connect.Request[v1.SetPrincipalStatusRequest]) (*connect.Response[v1.SetPrincipalStatusResponse], error)
	// GrantRole binds a role to a principal within a scope.
	GrantRole(context.Context, *connect.Request[v1.GrantRoleRequest]) (*connect.Response[v1.GrantRoleResponse], error)
	// IssueApiKey creates a machine credential. Its response is the only
	// place the usable key value ever appears.
	IssueApiKey(context.Context, *connect.Request[v1.IssueApiKeyRequest]) (*connect.Response[v1.IssueApiKeyResponse], error)
	// RevokeApiKey makes a key unusable immediately.
	RevokeApiKey(context.Context, *connect.Request[v1.RevokeApiKeyRequest]) (*connect.Response[v1.RevokeApiKeyResponse], error)
	// ListAudit returns the calling tenant's most recent audit records.
	ListAudit(context.Context, *connect.Request[v1.ListAuditRequest]) (*connect.Response[v1.ListAuditResponse], error)
}

// NewIdentityServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIdentityServiceHandler(svc IdentityServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	identityServiceMethods := v1.File_atsapbx_v1_identity_proto.Services().ByName("IdentityService").Methods()
	identityServiceAuthenticateUserHandler := connect.NewUnaryHandler(
		IdentityServiceAuthenticateUserProcedure,
		svc.AuthenticateUser,
		connect.WithSchema(identityServiceMethods.ByName("AuthenticateUser")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceProvisionTenantHandler := connect.NewUnaryHandler(
		IdentityServiceProvisionTenantProcedure,
		svc.ProvisionTenant,
		connect.WithSchema(identityServiceMethods.ByName("ProvisionTenant")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceProvisionPrincipalHandler := connect.NewUnaryHandler(
		IdentityServiceProvisionPrincipalProcedure,
		svc.ProvisionPrincipal,
		connect.WithSchema(identityServiceMethods.ByName("ProvisionPrincipal")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceSetTenantStatusHandler := connect.NewUnaryHandler(
		IdentityServiceSetTenantStatusProcedure,
		svc.SetTenantStatus,
		connect.WithSchema(identityServiceMethods.ByName("SetTenantStatus")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceSetPrincipalStatusHandler := connect.NewUnaryHandler(
		IdentityServiceSetPrincipalStatusProcedure,
		svc.SetPrincipalStatus,
		connect.WithSchema(identityServiceMethods.ByName("SetPrincipalStatus")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceGrantRoleHandler := connect.NewUnaryHandler(
		IdentityServiceGrantRoleProcedure,
		svc.GrantRole,
		connect.WithSchema(identityServiceMethods.ByName("GrantRole")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceIssueApiKeyHandler := connect.NewUnaryHandler(
		IdentityServiceIssueApiKeyProcedure,
		svc.IssueApiKey,
		connect.WithSchema(identityServiceMethods.ByName("IssueApiKey")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceRevokeApiKeyHandler := connect.NewUnaryHandler(
		IdentityServiceRevokeApiKeyProcedure,
		svc.RevokeApiKey,
		connect.WithSchema(identityServiceMethods.ByName("RevokeApiKey")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceListAuditHandler := connect.NewUnaryHandler(
		IdentityServiceListAuditProcedure,
		svc.ListAudit,
		connect.WithSchema(identityServiceMethods.ByName("ListAudit")),
		connect.WithHandlerOptions(opts...),
	)
	return "/atsapbx.v1.IdentityService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IdentityServiceAuthenticateUserProcedure:
			identityServiceAuthenticateUserHandler.ServeHTTP(w, r)
		case IdentityServiceProvisionTenantProcedure:
			identityServiceProvisionTenantHandler.ServeHTTP(w, r)
		case IdentityServiceProvisionPrincipalProcedure:
			identityServiceProvisionPrincipalHandler.ServeHTTP(w, r)
		case IdentityServiceSetTenantStatusProcedure:
			identityServiceSetTenantStatusHandler.ServeHTTP(w, r)
		case IdentityServiceSetPrincipalStatusProcedure:
			identityServiceSetPrincipalStatusHandler.ServeHTTP(w, r)
		case IdentityServiceGrantRoleProcedure:
			identityServiceGrantRoleHandler.ServeHTTP(w, r)
		case IdentityServiceIssueApiKeyProcedure:
			identityServiceIssueApiKeyHandler.ServeHTTP(w, r)
		case IdentityServiceRevokeApiKeyProcedure:
			identityServiceRevokeApiKeyHandler.ServeHTTP(w, r)
		case IdentityServiceListAuditProcedure:
			identityServiceListAuditHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIdentityServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIdentityServiceHandler struct{}

func (UnimplementedIdentityServiceHandler) AuthenticateUser(context.Context, *connect.Request[v1.AuthenticateUserRequest]) (*connect.Response[v1.AuthenticateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atsapbx.v1.IdentityService.AuthenticateUser is not implemented"))
}

func (UnimplementedIdentityServiceHandler) ProvisionTenant(context.Context, *connect.Request[v1.ProvisionTenantRequest]) (*connect.Response[v1.ProvisionTenantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atsapbx.v1.IdentityService.ProvisionTenant is not implemented"))
}

func (UnimplementedIdentityServiceHandler) ProvisionPrincipal(context.Context, *connect.Request[v1.ProvisionPrincipalRequest]) (*connect.Response[v1.ProvisionPrincipalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atsapbx.v1.IdentityService.ProvisionPrincipal is not implemented"))
}

func (UnimplementedIdentityServiceHandler) SetTenantStatus(context.Context, *connect.Request[v1.SetTenantStatusRequest]) (*connect.Response[v1.SetTenantStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atsapbx.v1.IdentityService.SetTenantStatus is not implemented"))
}

func (UnimplementedIdentityServiceHandler) SetPrincipalStatus(context.Context, *connect.Request[v1.SetPrincipalStatusRequest]) (*connect.Response[v1.SetPrincipalStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atsapbx.v1.IdentityService.SetPrincipalStatus is not implemented"))
}

func (UnimplementedIdentityServiceHandler) GrantRole(context.Context, *connect.Request[v1.GrantRoleRequest]) (*connect.Response[v1.GrantRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atsapbx.v1.IdentityService.GrantRole is not implemented"))
}

func (UnimplementedIdentityServiceHandler) IssueApiKey(context.Context, *connect.Request[v1.IssueApiKeyRequest]) (*connect.Response[v1.IssueApiKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atsapbx.v1.IdentityService.IssueApiKey is not implemented"))
}

func (UnimplementedIdentityServiceHandler) RevokeApiKey(context.Context, *connect.Request[v1.RevokeApiKeyRequest]) (*connect.Response[v1.RevokeApiKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atsapbx.v1.IdentityService.RevokeApiKey is not implemented"))
}

func (UnimplementedIdentityServiceHandler) ListAudit(context.Context, *connect.Request[v1.ListAuditRequest]) (*connect.Response[v1.ListAuditResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atsapbx.v1.IdentityService.ListAudit is not implemented"))
}
