// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: atsapbx/v1/pbx.proto

package atsapbxv1connect

import (
	v1 "atsap-api/internal/genproto/atsapbx/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PbxServiceName is the fully-qualified name of the PbxService service.
	PbxServiceName = "atsapbx.v1.PbxService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PbxServiceCreateExtensionProcedure is the fully-qualified name of the PbxService's
	// CreateExtension RPC.
	PbxServiceCreateExtensionProcedure = "/atsapbx.v1.PbxService/CreateExtension"
	// PbxServiceGetExtensionProcedure is the fully-qualified name of the PbxService's GetExtension RPC.
	PbxServiceGetExtensionProcedure = "/atsapbx.v1.PbxService/GetExtension"
	// PbxServiceListExtensionsProcedure is the fully-qualified name of the PbxService's ListExtensions
	// RPC.
	PbxServiceListExtensionsProcedure = "/atsapbx.v1.PbxService/ListExtensions"
	// PbxServiceUpdateExtensionProcedure is the fully-qualified name of the PbxService's
	// UpdateExtension RPC.
	PbxServiceUpdateExtensionProcedure = "/atsapbx.v1.PbxService/UpdateExtension"
	// PbxServiceDeleteExtensionProcedure is the fully-qualified name of the PbxService's
	// DeleteExtension RPC.
	PbxServiceDeleteExtensionProcedure = "/atsapbx.v1.PbxService/DeleteExtension"
	// PbxServiceRegenerateSecretProcedure is the fully-qualified name of the PbxService's
	// RegenerateSecret RPC.
	PbxServiceRegenerateSecretProcedure = "/atsapbx.v1.PbxService/RegenerateSecret"
)

// PbxServiceClient is a client for the atsapbx.v1.PbxService service.
type PbxServiceClient interface {
	// CreateExtension provisions an extension and makes it registrable by
	// a device. No apply step follows: it is live when this returns.
	CreateExtension(context.Context, *connect.Request[v1.CreateExtensionRequest]) (*connect.Response[v1.CreateExtensionResponse], error)
	// GetExtension reads one extension, including whether a device is
	// currently registered to it.
	GetExtension(context.Context, *connect.Request[v1.GetExtensionRequest]) (*connect.Response[v1.GetExtensionResponse], error)
	// ListExtensions returns a page of the calling tenant's extensions.
	ListExtensions(context.Context, *connect.Request[v1.ListExtensionsRequest]) (*connect.Response[v1.ListExtensionsResponse], error)
	// UpdateExtension changes an extension's display name or device type.
	// The number is immutable: renumbering would orphan every device
	// already provisioned against it, so it is a delete plus a create.
	UpdateExtension(context.Context, *connect.Request[v1.UpdateExtensionRequest]) (*connect.Response[v1.UpdateExtensionResponse], error)
	// DeleteExtension removes an extension and deprovisions it. A device
	// holding its former credential can no longer register, immediately.
	DeleteExtension(context.Context, *connect.Request[v1.DeleteExtensionRequest]) (*connect.Response[v1.DeleteExtensionResponse], error)
	// RegenerateSecret issues a new credential. The previous one stops
	// working the moment this returns — two live credentials for one
	// extension is the state a rotation exists to end.
	RegenerateSecret(context.Context, *connect.Request[v1.RegenerateSecretRequest]) (*connect.Response[v1.RegenerateSecretResponse], error)
}

// NewPbxServiceClient constructs a client for the atsapbx.v1.PbxService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPbxServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PbxServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	pbxServiceMethods := v1.File_atsapbx_v1_pbx_proto.Services().ByName("PbxService").Methods()
	return &pbxServiceClient{
		createExtension: connect.NewClient[v1.CreateExtensionRequest, v1.CreateExtensionResponse](
			httpClient,
			baseURL+PbxServiceCreateExtensionProcedure,
			connect.WithSchema(pbxServiceMethods.ByName("CreateExtension")),
			connect.WithClientOptions(opts...),
		),
		getExtension: connect.NewClient[v1.GetExtensionRequest, v1.GetExtensionResponse](
			httpClient,
			baseURL+PbxServiceGetExtensionProcedure,
			connect.WithSchema(pbxServiceMethods.ByName("GetExtension")),
			connect.WithClientOptions(opts...),
		),
		listExtensions: connect.NewClient[v1.ListExtensionsRequest, v1.ListExtensionsResponse](
			httpClient,
			baseURL+PbxServiceListExtensionsProcedure,
			connect.WithSchema(pbxServiceMethods.ByName("ListExtensions")),
			connect.WithClientOptions(opts...),
		),
		updateExtension: connect.NewClient[v1.UpdateExtensionRequest, v1.UpdateExtensionResponse](
			httpClient,
			baseURL+PbxServiceUpdateExtensionProcedure,
			connect.WithSchema(pbxServiceMethods.ByName("UpdateExtension")),
			connect.WithClientOptions(opts...),
		),
		deleteExtension: connect.NewClient[v1.DeleteExtensionRequest, v1.DeleteExtensionResponse](
			httpClient,
			baseURL+PbxServiceDeleteExtensionProcedure,
			connect.WithSchema(pbxServiceMethods.ByName("DeleteExtension")),
			connect.WithClientOptions(opts...),
		),
		regenerateSecret: connect.NewClient[v1.RegenerateSecretRequest, v1.RegenerateSecretResponse](
			httpClient,
			baseURL+PbxServiceRegenerateSecretProcedure,
			connect.WithSchema(pbxServiceMethods.ByName("RegenerateSecret")),
			connect.WithClientOptions(opts...),
		),
	}
}

// pbxServiceClient implements PbxServiceClient.
type pbxServiceClient struct {
	createExtension  *connect.Client[v1.CreateExtensionRequest, v1.CreateExtensionResponse]
	getExtension     *connect.Client[v1.GetExtensionRequest, v1.GetExtensionResponse]
	listExtensions   *connect.Client[v1.ListExtensionsRequest, v1.ListExtensionsResponse]
	updateExtension  *connect.Client[v1.UpdateExtensionRequest, v1.UpdateExtensionResponse]
	deleteExtension  *connect.Client[v1.DeleteExtensionRequest, v1.DeleteExtensionResponse]
	regenerateSecret *connect.Client[v1.RegenerateSecretRequest, v1.RegenerateSecretResponse]
}

// CreateExtension calls atsapbx.v1.PbxService.CreateExtension.
func (c *pbxServiceClient) CreateExtension(ctx context.Context, req *connect.Request[v1.CreateExtensionRequest]) (*connect.Response[v1.CreateExtensionResponse], error) {
	return c.createExtension.CallUnary(ctx, req)
}

// GetExtension calls atsapbx.v1.PbxService.GetExtension.
func (c *pbxServiceClient) GetExtension(ctx context.Context, req *connect.Request[v1.GetExtensionRequest]) (*connect.Response[v1.GetExtensionResponse], error) {
	return c.getExtension.CallUnary(ctx, req)
}

// ListExtensions calls atsapbx.v1.PbxService.ListExtensions.
func (c *pbxServiceClient) ListExtensions(ctx context.Context, req *connect.Request[v1.ListExtensionsRequest]) (*connect.Response[v1.ListExtensionsResponse], error) {
	return c.listExtensions.CallUnary(ctx, req)
}

// UpdateExtension calls atsapbx.v1.PbxService.UpdateExtension.
func (c *pbxServiceClient) UpdateExtension(ctx context.Context, req *connect.Request[v1.UpdateExtensionRequest]) (*connect.Response[v1.UpdateExtensionResponse], error) {
	return c.updateExtension.CallUnary(ctx, req)
}

// DeleteExtension calls atsapbx.v1.PbxService.DeleteExtension.
func (c *pbxServiceClient) DeleteExtension(ctx context.Context, req *connect.Request[v1.DeleteExtensionRequest]) (*connect.Response[v1.DeleteExtensionResponse], error) {
	return c.deleteExtension.CallUnary(ctx, req)
}

// RegenerateSecret calls atsapbx.v1.PbxService.RegenerateSecret.
func (c *pbxServiceClient) RegenerateSecret(ctx context.Context, req *connect.Request[v1.RegenerateSecretRequest]) (*connect.Response[v1.RegenerateSecretResponse], error) {
	return c.regenerateSecret.CallUnary(ctx, req)
}

// PbxServiceHandler is an implementation of the atsapbx.v1.PbxService service.
type PbxServiceHandler interface {
	// CreateExtension provisions an extension and makes it registrable by
	// a device. No apply step follows: it is live when this returns.
	CreateExtension(context.Context, *connect.Request[v1.CreateExtensionRequest]) (*connect.Response[v1.CreateExtensionResponse], error)
	// GetExtension reads one extension, including whether a device is
	// currently registered to it.
	GetExtension(context.Context, *connect.Request[v1.GetExtensionRequest]) (*connect.Response[v1.GetExtensionResponse], error)
	// ListExtensions returns a page of the calling tenant's extensions.
	ListExtensions(context.Context, *connect.Request[v1.ListExtensionsRequest]) (*connect.Response[v1.ListExtensionsResponse], error)
	// UpdateExtension changes an extension's display name or device type.
	// The number is immutable: renumbering would orphan every device
	// already provisioned against it, so it is a delete plus a create.
	UpdateExtension(context.Context, *connect.Request[v1.UpdateExtensionRequest]) (*connect.Response[v1.UpdateExtensionResponse], error)
	// DeleteExtension removes an extension and deprovisions it. A device
	// holding its former credential can no longer register, immediately.
	DeleteExtension(context.Context, *connect.Request[v1.DeleteExtensionRequest]) (*connect.Response[v1.DeleteExtensionResponse], error)
	// RegenerateSecret issues a new credential. The previous one stops
	// working the moment this returns — two live credentials for one
	// extension is the state a rotation exists to end.
	RegenerateSecret(context.Context, *connect.Request[v1.RegenerateSecretRequest]) (*connect.Response[v1.RegenerateSecretResponse], error)
}

// NewPbxServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPbxServiceHandler(svc PbxServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pbxServiceMethods := v1.File_atsapbx_v1_pbx_proto.Services().ByName("PbxService").Methods()
	pbxServiceCreateExtensionHandler := connect.NewUnaryHandler(
		PbxServiceCreateExtensionProcedure,
		svc.CreateExtension,
		connect.WithSchema(pbxServiceMethods.ByName("CreateExtension")),
		connect.WithHandlerOptions(opts...),
	)
	pbxServiceGetExtensionHandler := connect.NewUnaryHandler(
		PbxServiceGetExtensionProcedure,
		svc.GetExtension,
		connect.WithSchema(pbxServiceMethods.ByName("GetExtension")),
		connect.WithHandlerOptions(opts...),
	)
	pbxServiceListExtensionsHandler := connect.NewUnaryHandler(
		PbxServiceListExtensionsProcedure,
		svc.ListExtensions,
		connect.WithSchema(pbxServiceMethods.ByName("ListExtensions")),
		connect.WithHandlerOptions(opts...),
	)
	pbxServiceUpdateExtensionHandler := connect.NewUnaryHandler(
		PbxServiceUpdateExtensionProcedure,
		svc.UpdateExtension,
		connect.WithSchema(pbxServiceMethods.ByName("UpdateExtension")),
		connect.WithHandlerOptions(opts...),
	)
	pbxServiceDeleteExtensionHandler := connect.NewUnaryHandler(
		PbxServiceDeleteExtensionProcedure,
		svc.DeleteExtension,
		connect.WithSchema(pbxServiceMethods.ByName("DeleteExtension")),
		connect.WithHandlerOptions(opts...),
	)
	pbxServiceRegenerateSecretHandler := connect.NewUnaryHandler(
		PbxServiceRegenerateSecretProcedure,
		svc.RegenerateSecret,
		connect.WithSchema(pbxServiceMethods.ByName("RegenerateSecret")),
		connect.WithHandlerOptions(opts...),
	)
	return "/atsapbx.v1.PbxService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PbxServiceCreateExtensionProcedure:
			pbxServiceCreateExtensionHandler.ServeHTTP(w, r)
		case PbxServiceGetExtensionProcedure:
			pbxServiceGetExtensionHandler.ServeHTTP(w, r)
		case PbxServiceListExtensionsProcedure:
			pbxServiceListExtensionsHandler.ServeHTTP(w, r)
		case PbxServiceUpdateExtensionProcedure:
			pbxServiceUpdateExtensionHandler.ServeHTTP(w, r)
		case PbxServiceDeleteExtensionProcedure:
			pbxServiceDeleteExtensionHandler.ServeHTTP(w, r)
		case PbxServiceRegenerateSecretProcedure:
			pbxServiceRegenerateSecretHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPbxServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPbxServiceHandler struct{}

func (UnimplementedPbxServiceHandler) CreateExtension(context.Context, *connect.Request[v1.CreateExtensionRequest]) (*connect.Response[v1.CreateExtensionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atsapbx.v1.PbxService.CreateExtension is not implemented"))
}

func (UnimplementedPbxServiceHandler) GetExtension(context.Context, *connect.Request[v1.GetExtensionRequest]) (*connect.Response[v1.GetExtensionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atsapbx.v1.PbxService.GetExtension is not implemented"))
}

func (UnimplementedPbxServiceHandler) ListExtensions(context.Context, *connect.Request[v1.ListExtensionsRequest]) (*connect.Response[v1.ListExtensionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atsapbx.v1.PbxService.ListExtensions is not implemented"))
}

func (UnimplementedPbxServiceHandler) UpdateExtension(context.Context, *connect.Request[v1.UpdateExtensionRequest]) (*connect.Response[v1.UpdateExtensionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atsapbx.v1.PbxService.UpdateExtension is not implemented"))
}

func (UnimplementedPbxServiceHandler) DeleteExtension(context.Context, *connect.Request[v1.DeleteExtensionRequest]) (*connect.Response[v1.DeleteExtensionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atsapbx.v1.PbxService.DeleteExtension is not implemented"))
}

func (UnimplementedPbxServiceHandler) RegenerateSecret(context.Context, *connect.Request[v1.RegenerateSecretRequest]) (*connect.Response[v1.RegenerateSecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atsapbx.v1.PbxService.RegenerateSecret is not implemented"))
}
