// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: atsapbx/v1/telephony.proto

package atsapbxv1connect

import (
	v1 "atsap-api/internal/genproto/atsapbx/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TelephonyServiceName is the fully-qualified name of the TelephonyService service.
	TelephonyServiceName = "atsapbx.v1.TelephonyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TelephonyServiceGetCallProcedure is the fully-qualified name of the TelephonyService's GetCall
	// RPC.
	TelephonyServiceGetCallProcedure = "/atsapbx.v1.TelephonyService/GetCall"
)

// TelephonyServiceClient is a client for the atsapbx.v1.TelephonyService service.
type TelephonyServiceClient interface {
	// GetCall returns a Call's current state and participants.
	GetCall(context.Context, *connect.Request[v1.GetCallRequest]) (*connect.Response[v1.GetCallResponse], error)
}

// NewTelephonyServiceClient constructs a client for the atsapbx.v1.TelephonyService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTelephonyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TelephonyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	telephonyServiceMethods := v1.File_atsapbx_v1_telephony_proto.Services().ByName("TelephonyService").Methods()
	return &telephonyServiceClient{
		getCall: connect.NewClient[v1.GetCallRequest, v1.GetCallResponse](
			httpClient,
			baseURL+TelephonyServiceGetCallProcedure,
			connect.WithSchema(telephonyServiceMethods.ByName("GetCall")),
			connect.WithClientOptions(opts...),
		),
	}
}

// telephonyServiceClient implements TelephonyServiceClient.
type telephonyServiceClient struct {
	getCall *connect.Client[v1.GetCallRequest, v1.GetCallResponse]
}

// GetCall calls atsapbx.v1.TelephonyService.GetCall.
func (c *telephonyServiceClient) GetCall(ctx context.Context, req *connect.Request[v1.GetCallRequest]) (*connect.Response[v1.GetCallResponse], error) {
	return c.getCall.CallUnary(ctx, req)
}

// TelephonyServiceHandler is an implementation of the atsapbx.v1.TelephonyService service.
type TelephonyServiceHandler interface {
	// GetCall returns a Call's current state and participants.
	GetCall(context.Context, *connect.Request[v1.GetCallRequest]) (*connect.Response[v1.GetCallResponse], error)
}

// NewTelephonyServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTelephonyServiceHandler(svc TelephonyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	telephonyServiceMethods := v1.File_atsapbx_v1_telephony_proto.Services().ByName("TelephonyService").Methods()
	telephonyServiceGetCallHandler := connect.NewUnaryHandler(
		TelephonyServiceGetCallProcedure,
		svc.GetCall,
		connect.WithSchema(telephonyServiceMethods.ByName("GetCall")),
		connect.WithHandlerOptions(opts...),
	)
	return "/atsapbx.v1.TelephonyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TelephonyServiceGetCallProcedure:
			telephonyServiceGetCallHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTelephonyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTelephonyServiceHandler struct{}

func (UnimplementedTelephonyServiceHandler) GetCall(context.Context, *connect.Request[v1.GetCallRequest]) (*connect.Response[v1.GetCallResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atsapbx.v1.TelephonyService.GetCall is not implemented"))
}
