// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: atsapbx/v1/identity.proto

package atsapbxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TenantStatus mirrors the domain's tenant lifecycle.
type TenantStatus int32

const (
	TenantStatus_TENANT_STATUS_UNSPECIFIED TenantStatus = 0
	TenantStatus_TENANT_STATUS_ACTIVE      TenantStatus = 1
	TenantStatus_TENANT_STATUS_SUSPENDED   TenantStatus = 2
)

// Enum value maps for TenantStatus.
var (
	TenantStatus_name = map[int32]string{
		0: "TENANT_STATUS_UNSPECIFIED",
		1: "TENANT_STATUS_ACTIVE",
		2: "TENANT_STATUS_SUSPENDED",
	}
	TenantStatus_value = map[string]int32{
		"TENANT_STATUS_UNSPECIFIED": 0,
		"TENANT_STATUS_ACTIVE":      1,
		"TENANT_STATUS_SUSPENDED":   2,
	}
)

func (x TenantStatus) Enum() *TenantStatus {
	p := new(TenantStatus)
	*p = x
	return p
}

func (x TenantStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TenantStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_atsapbx_v1_identity_proto_enumTypes[0].Descriptor()
}

func (TenantStatus) Type() protoreflect.EnumType {
	return &file_atsapbx_v1_identity_proto_enumTypes[0]
}

func (x TenantStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TenantStatus.Descriptor instead.
func (TenantStatus) EnumDescriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{0}
}

// PrincipalStatus mirrors the domain's principal lifecycle.
type PrincipalStatus int32

const (
	PrincipalStatus_PRINCIPAL_STATUS_UNSPECIFIED PrincipalStatus = 0
	PrincipalStatus_PRINCIPAL_STATUS_ACTIVE      PrincipalStatus = 1
	PrincipalStatus_PRINCIPAL_STATUS_DISABLED    PrincipalStatus = 2
)

// Enum value maps for PrincipalStatus.
var (
	PrincipalStatus_name = map[int32]string{
		0: "PRINCIPAL_STATUS_UNSPECIFIED",
		1: "PRINCIPAL_STATUS_ACTIVE",
		2: "PRINCIPAL_STATUS_DISABLED",
	}
	PrincipalStatus_value = map[string]int32{
		"PRINCIPAL_STATUS_UNSPECIFIED": 0,
		"PRINCIPAL_STATUS_ACTIVE":      1,
		"PRINCIPAL_STATUS_DISABLED":    2,
	}
)

func (x PrincipalStatus) Enum() *PrincipalStatus {
	p := new(PrincipalStatus)
	*p = x
	return p
}

func (x PrincipalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrincipalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_atsapbx_v1_identity_proto_enumTypes[1].Descriptor()
}

func (PrincipalStatus) Type() protoreflect.EnumType {
	return &file_atsapbx_v1_identity_proto_enumTypes[1]
}

func (x PrincipalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrincipalStatus.Descriptor instead.
func (PrincipalStatus) EnumDescriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{1}
}

// Tenant is a partner organisation.
type Tenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        TenantStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=atsapbx.v1.TenantStatus" json:"status,omitempty"`
	ResidencyZone string                 `protobuf:"bytes,4,opt,name=residency_zone,json=residencyZone,proto3" json:"residency_zone,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_atsapbx_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *Tenant) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetStatus() TenantStatus {
	if x != nil {
		return x.Status
	}
	return TenantStatus_TENANT_STATUS_UNSPECIFIED
}

func (x *Tenant) GetResidencyZone() string {
	if x != nil {
		return x.ResidencyZone
	}
	return ""
}

func (x *Tenant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Principal is a user account. It carries no credential representation:
// there is deliberately no password or hash field here.
type Principal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrincipalId   string                 `protobuf:"bytes,1,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Status        PrincipalStatus        `protobuf:"varint,6,opt,name=status,proto3,enum=atsapbx.v1.PrincipalStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Principal) Reset() {
	*x = Principal{}
	mi := &file_atsapbx_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Principal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Principal) ProtoMessage() {}

func (x *Principal) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Principal.ProtoReflect.Descriptor instead.
func (*Principal) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *Principal) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *Principal) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Principal) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Principal) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Principal) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Principal) GetStatus() PrincipalStatus {
	if x != nil {
		return x.Status
	}
	return PrincipalStatus_PRINCIPAL_STATUS_UNSPECIFIED
}

func (x *Principal) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AuthenticateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tenant_id is explicit because usernames are unique per tenant, never
	// globally (AC-01.2) — two tenants may each have an "admin", and
	// without a tenant there is no single account to resolve to.
	TenantId      string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Username      string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateUserRequest) Reset() {
	*x = AuthenticateUserRequest{}
	mi := &file_atsapbx_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateUserRequest) ProtoMessage() {}

func (x *AuthenticateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateUserRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateUserRequest) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticateUserRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AuthenticateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthenticateUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token is credential material. Never log it, never store it.
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PrincipalId   string                 `protobuf:"bytes,4,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateUserResponse) Reset() {
	*x = AuthenticateUserResponse{}
	mi := &file_atsapbx_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateUserResponse) ProtoMessage() {}

func (x *AuthenticateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateUserResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateUserResponse) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *AuthenticateUserResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthenticateUserResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *AuthenticateUserResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AuthenticateUserResponse) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

type ProvisionTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ResidencyZone string                 `protobuf:"bytes,2,opt,name=residency_zone,json=residencyZone,proto3" json:"residency_zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionTenantRequest) Reset() {
	*x = ProvisionTenantRequest{}
	mi := &file_atsapbx_v1_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionTenantRequest) ProtoMessage() {}

func (x *ProvisionTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionTenantRequest.ProtoReflect.Descriptor instead.
func (*ProvisionTenantRequest) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{4}
}

func (x *ProvisionTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProvisionTenantRequest) GetResidencyZone() string {
	if x != nil {
		return x.ResidencyZone
	}
	return ""
}

type ProvisionTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionTenantResponse) Reset() {
	*x = ProvisionTenantResponse{}
	mi := &file_atsapbx_v1_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionTenantResponse) ProtoMessage() {}

func (x *ProvisionTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionTenantResponse.ProtoReflect.Descriptor instead.
func (*ProvisionTenantResponse) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{5}
}

func (x *ProvisionTenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type ProvisionPrincipalRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Username string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email    string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// password is accepted here and never echoed back: the response
	// carries a Principal, which has no field for it.
	Password      string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Role          string `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionPrincipalRequest) Reset() {
	*x = ProvisionPrincipalRequest{}
	mi := &file_atsapbx_v1_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionPrincipalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionPrincipalRequest) ProtoMessage() {}

func (x *ProvisionPrincipalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionPrincipalRequest.ProtoReflect.Descriptor instead.
func (*ProvisionPrincipalRequest) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{6}
}

func (x *ProvisionPrincipalRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ProvisionPrincipalRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProvisionPrincipalRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ProvisionPrincipalRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ProvisionPrincipalRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ProvisionPrincipalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     *Principal             `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionPrincipalResponse) Reset() {
	*x = ProvisionPrincipalResponse{}
	mi := &file_atsapbx_v1_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionPrincipalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionPrincipalResponse) ProtoMessage() {}

func (x *ProvisionPrincipalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionPrincipalResponse.ProtoReflect.Descriptor instead.
func (*ProvisionPrincipalResponse) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{7}
}

func (x *ProvisionPrincipalResponse) GetPrincipal() *Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

type SetTenantStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        TenantStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=atsapbx.v1.TenantStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTenantStatusRequest) Reset() {
	*x = SetTenantStatusRequest{}
	mi := &file_atsapbx_v1_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTenantStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTenantStatusRequest) ProtoMessage() {}

func (x *SetTenantStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTenantStatusRequest.ProtoReflect.Descriptor instead.
func (*SetTenantStatusRequest) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{8}
}

func (x *SetTenantStatusRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SetTenantStatusRequest) GetStatus() TenantStatus {
	if x != nil {
		return x.Status
	}
	return TenantStatus_TENANT_STATUS_UNSPECIFIED
}

type SetTenantStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTenantStatusResponse) Reset() {
	*x = SetTenantStatusResponse{}
	mi := &file_atsapbx_v1_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTenantStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTenantStatusResponse) ProtoMessage() {}

func (x *SetTenantStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTenantStatusResponse.ProtoReflect.Descriptor instead.
func (*SetTenantStatusResponse) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{9}
}

func (x *SetTenantStatusResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type SetPrincipalStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PrincipalId   string                 `protobuf:"bytes,2,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	Status        PrincipalStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=atsapbx.v1.PrincipalStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPrincipalStatusRequest) Reset() {
	*x = SetPrincipalStatusRequest{}
	mi := &file_atsapbx_v1_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPrincipalStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPrincipalStatusRequest) ProtoMessage() {}

func (x *SetPrincipalStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPrincipalStatusRequest.ProtoReflect.Descriptor instead.
func (*SetPrincipalStatusRequest) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{10}
}

func (x *SetPrincipalStatusRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SetPrincipalStatusRequest) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *SetPrincipalStatusRequest) GetStatus() PrincipalStatus {
	if x != nil {
		return x.Status
	}
	return PrincipalStatus_PRINCIPAL_STATUS_UNSPECIFIED
}

type SetPrincipalStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     *Principal             `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPrincipalStatusResponse) Reset() {
	*x = SetPrincipalStatusResponse{}
	mi := &file_atsapbx_v1_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPrincipalStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPrincipalStatusResponse) ProtoMessage() {}

func (x *SetPrincipalStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPrincipalStatusResponse.ProtoReflect.Descriptor instead.
func (*SetPrincipalStatusResponse) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{11}
}

func (x *SetPrincipalStatusResponse) GetPrincipal() *Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

type GrantRoleRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TenantId    string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PrincipalId string                 `protobuf:"bytes,2,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	Role        string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	// scope is "tenant" when omitted; "system" is platform-operator
	// authority and is not grantable by a tenant's own administrators.
	Scope         string `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantRoleRequest) Reset() {
	*x = GrantRoleRequest{}
	mi := &file_atsapbx_v1_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRoleRequest) ProtoMessage() {}

func (x *GrantRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRoleRequest.ProtoReflect.Descriptor instead.
func (*GrantRoleRequest) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{12}
}

func (x *GrantRoleRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GrantRoleRequest) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *GrantRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GrantRoleRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type GrantRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantRoleResponse) Reset() {
	*x = GrantRoleResponse{}
	mi := &file_atsapbx_v1_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRoleResponse) ProtoMessage() {}

func (x *GrantRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRoleResponse.ProtoReflect.Descriptor instead.
func (*GrantRoleResponse) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{13}
}

type IssueApiKeyRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TenantId    string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PrincipalId string                 `protobuf:"bytes,2,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	// expires_at is optional; omitted means the key does not expire on its
	// own and must be revoked to stop working.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueApiKeyRequest) Reset() {
	*x = IssueApiKeyRequest{}
	mi := &file_atsapbx_v1_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueApiKeyRequest) ProtoMessage() {}

func (x *IssueApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueApiKeyRequest.ProtoReflect.Descriptor instead.
func (*IssueApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{14}
}

func (x *IssueApiKeyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IssueApiKeyRequest) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *IssueApiKeyRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type IssueApiKeyResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ApiKeyId string                 `protobuf:"bytes,1,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	// raw_key is the usable credential, returned here and nowhere else,
	// ever. Losing it means issuing a new key — it cannot be recovered
	// from what is stored.
	RawKey        string                 `protobuf:"bytes,2,opt,name=raw_key,json=rawKey,proto3" json:"raw_key,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueApiKeyResponse) Reset() {
	*x = IssueApiKeyResponse{}
	mi := &file_atsapbx_v1_identity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueApiKeyResponse) ProtoMessage() {}

func (x *IssueApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_identity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueApiKeyResponse.ProtoReflect.Descriptor instead.
func (*IssueApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{15}
}

func (x *IssueApiKeyResponse) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

func (x *IssueApiKeyResponse) GetRawKey() string {
	if x != nil {
		return x.RawKey
	}
	return ""
}

func (x *IssueApiKeyResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type RevokeApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ApiKeyId      string                 `protobuf:"bytes,2,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeApiKeyRequest) Reset() {
	*x = RevokeApiKeyRequest{}
	mi := &file_atsapbx_v1_identity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeApiKeyRequest) ProtoMessage() {}

func (x *RevokeApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_identity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeApiKeyRequest.ProtoReflect.Descriptor instead.
func (*RevokeApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{16}
}

func (x *RevokeApiKeyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RevokeApiKeyRequest) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

type RevokeApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeApiKeyResponse) Reset() {
	*x = RevokeApiKeyResponse{}
	mi := &file_atsapbx_v1_identity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeApiKeyResponse) ProtoMessage() {}

func (x *RevokeApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_identity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeApiKeyResponse.ProtoReflect.Descriptor instead.
func (*RevokeApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{17}
}

// AuditRecord is one immutable administrative mutation. Credential
// material is stripped before the record is written, so before_state and
// after_state never contain it.
type AuditRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId        string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ActorId         string                 `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorType       string                 `protobuf:"bytes,4,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	Action          string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	ResourceType    string                 `protobuf:"bytes,6,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId      string                 `protobuf:"bytes,7,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	BeforeStateJson string                 `protobuf:"bytes,8,opt,name=before_state_json,json=beforeStateJson,proto3" json:"before_state_json,omitempty"`
	AfterStateJson  string                 `protobuf:"bytes,9,opt,name=after_state_json,json=afterStateJson,proto3" json:"after_state_json,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuditRecord) Reset() {
	*x = AuditRecord{}
	mi := &file_atsapbx_v1_identity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRecord) ProtoMessage() {}

func (x *AuditRecord) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_identity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRecord.ProtoReflect.Descriptor instead.
func (*AuditRecord) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{18}
}

func (x *AuditRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuditRecord) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AuditRecord) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AuditRecord) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *AuditRecord) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditRecord) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *AuditRecord) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *AuditRecord) GetBeforeStateJson() string {
	if x != nil {
		return x.BeforeStateJson
	}
	return ""
}

func (x *AuditRecord) GetAfterStateJson() string {
	if x != nil {
		return x.AfterStateJson
	}
	return ""
}

func (x *AuditRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListAuditRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// limit defaults to a server-chosen bound when zero. No cursor: a
	// partner needing pagination will say so, and guessing the shape now
	// freezes a contract nobody has asked for (D-25).
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditRequest) Reset() {
	*x = ListAuditRequest{}
	mi := &file_atsapbx_v1_identity_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditRequest) ProtoMessage() {}

func (x *ListAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_identity_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditRequest.ProtoReflect.Descriptor instead.
func (*ListAuditRequest) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{19}
}

func (x *ListAuditRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListAuditRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListAuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*AuditRecord         `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditResponse) Reset() {
	*x = ListAuditResponse{}
	mi := &file_atsapbx_v1_identity_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditResponse) ProtoMessage() {}

func (x *ListAuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_identity_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditResponse.ProtoReflect.Descriptor instead.
func (*ListAuditResponse) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_identity_proto_rawDescGZIP(), []int{20}
}

func (x *ListAuditResponse) GetRecords() []*AuditRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_atsapbx_v1_identity_proto protoreflect.FileDescriptor

const file_atsapbx_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\x19atsapbx/v1/identity.proto\x12\n" +
	"atsapbx.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x01\n" +
	"\x06Tenant\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.atsapbx.v1.TenantStatusR\x06status\x12%\n" +
	"\x0eresidency_zone\x18\x04 \x01(\tR\rresidencyZone\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x81\x02\n" +
	"\tPrincipal\x12!\n" +
	"\fprincipal_id\x18\x01 \x01(\tR\vprincipalId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x123\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1b.atsapbx.v1.PrincipalStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"n\n" +
	"\x17AuthenticateUserRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\xab\x01\n" +
	"\x18AuthenticateUserResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12!\n" +
	"\fprincipal_id\x18\x04 \x01(\tR\vprincipalId\"S\n" +
	"\x16ProvisionTenantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eresidency_zone\x18\x02 \x01(\tR\rresidencyZone\"E\n" +
	"\x17ProvisionTenantResponse\x12*\n" +
	"\x06tenant\x18\x01 \x01(\v2\x12.atsapbx.v1.TenantR\x06tenant\"\x9a\x01\n" +
	"\x19ProvisionPrincipalRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"Q\n" +
	"\x1aProvisionPrincipalResponse\x123\n" +
	"\tprincipal\x18\x01 \x01(\v2\x15.atsapbx.v1.PrincipalR\tprincipal\"g\n" +
	"\x16SetTenantStatusRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.atsapbx.v1.TenantStatusR\x06status\"E\n" +
	"\x17SetTenantStatusResponse\x12*\n" +
	"\x06tenant\x18\x01 \x01(\v2\x12.atsapbx.v1.TenantR\x06tenant\"\x90\x01\n" +
	"\x19SetPrincipalStatusRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fprincipal_id\x18\x02 \x01(\tR\vprincipalId\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.atsapbx.v1.PrincipalStatusR\x06status\"Q\n" +
	"\x1aSetPrincipalStatusResponse\x123\n" +
	"\tprincipal\x18\x01 \x01(\v2\x15.atsapbx.v1.PrincipalR\tprincipal\"|\n" +
	"\x10GrantRoleRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fprincipal_id\x18\x02 \x01(\tR\vprincipalId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\"\x13\n" +
	"\x11GrantRoleResponse\"\x8f\x01\n" +
	"\x12IssueApiKeyRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fprincipal_id\x18\x02 \x01(\tR\vprincipalId\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x87\x01\n" +
	"\x13IssueApiKeyResponse\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x01 \x01(\tR\bapiKeyId\x12\x17\n" +
	"\araw_key\x18\x02 \x01(\tR\x06rawKey\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"P\n" +
	"\x13RevokeApiKeyRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x02 \x01(\tR\bapiKeyId\"\x16\n" +
	"\x14RevokeApiKeyResponse\"\xe3\x02\n" +
	"\vAuditRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x04 \x01(\tR\tactorType\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12#\n" +
	"\rresource_type\x18\x06 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\a \x01(\tR\n" +
	"resourceId\x12*\n" +
	"\x11before_state_json\x18\b \x01(\tR\x0fbeforeStateJson\x12(\n" +
	"\x10after_state_json\x18\t \x01(\tR\x0eafterStateJson\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"E\n" +
	"\x10ListAuditRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"F\n" +
	"\x11ListAuditResponse\x121\n" +
	"\arecords\x18\x01 \x03(\v2\x17.atsapbx.v1.AuditRecordR\arecords*d\n" +
	"\fTenantStatus\x12\x1d\n" +
	"\x19TENANT_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TENANT_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17TENANT_STATUS_SUSPENDED\x10\x02*o\n" +
	"\x0fPrincipalStatus\x12 \n" +
	"\x1cPRINCIPAL_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PRINCIPAL_STATUS_ACTIVE\x10\x01\x12\x1d\n" +
	"\x19PRINCIPAL_STATUS_DISABLED\x10\x022\xa9\x06\n" +
	"\x0fIdentityService\x12]\n" +
	"\x10AuthenticateUser\x12#.atsapbx.v1.AuthenticateUserRequest\x1a$.atsapbx.v1.AuthenticateUserResponse\x12Z\n" +
	"\x0fProvisionTenant\x12\".atsapbx.v1.ProvisionTenantRequest\x1a#.atsapbx.v1.ProvisionTenantResponse\x12c\n" +
	"\x12ProvisionPrincipal\x12%.atsapbx.v1.ProvisionPrincipalRequest\x1a&.atsapbx.v1.ProvisionPrincipalResponse\x12Z\n" +
	"\x0fSetTenantStatus\x12\".atsapbx.v1.SetTenantStatusRequest\x1a#.atsapbx.v1.SetTenantStatusResponse\x12c\n" +
	"\x12SetPrincipalStatus\x12%.atsapbx.v1.SetPrincipalStatusRequest\x1a&.atsapbx.v1.SetPrincipalStatusResponse\x12H\n" +
	"\tGrantRole\x12\x1c.atsapbx.v1.GrantRoleRequest\x1a\x1d.atsapbx.v1.GrantRoleResponse\x12N\n" +
	"\vIssueApiKey\x12\x1e.atsapbx.v1.IssueApiKeyRequest\x1a\x1f.atsapbx.v1.IssueApiKeyResponse\x12Q\n" +
	"\fRevokeApiKey\x12\x1f.atsapbx.v1.RevokeApiKeyRequest\x1a .atsapbx.v1.RevokeApiKeyResponse\x12H\n" +
	"\tListAudit\x12\x1c.atsapbx.v1.ListAuditRequest\x1a\x1d.atsapbx.v1.ListAuditResponseB2Z0atsap-api/internal/genproto/atsapbx/v1;atsapbxv1b\x06proto3"

var (
	file_atsapbx_v1_identity_proto_rawDescOnce sync.Once
	file_atsapbx_v1_identity_proto_rawDescData []byte
)

func file_atsapbx_v1_identity_proto_rawDescGZIP() []byte {
	file_atsapbx_v1_identity_proto_rawDescOnce.Do(func() {
		file_atsapbx_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atsapbx_v1_identity_proto_rawDesc), len(file_atsapbx_v1_identity_proto_rawDesc)))
	})
	return file_atsapbx_v1_identity_proto_rawDescData
}

var file_atsapbx_v1_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_atsapbx_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_atsapbx_v1_identity_proto_goTypes = []any{
	(TenantStatus)(0),                  // 0: atsapbx.v1.TenantStatus
	(PrincipalStatus)(0),               // 1: atsapbx.v1.PrincipalStatus
	(*Tenant)(nil),                     // 2: atsapbx.v1.Tenant
	(*Principal)(nil),                  // 3: atsapbx.v1.Principal
	(*AuthenticateUserRequest)(nil),    // 4: atsapbx.v1.AuthenticateUserRequest
	(*AuthenticateUserResponse)(nil),   // 5: atsapbx.v1.AuthenticateUserResponse
	(*ProvisionTenantRequest)(nil),     // 6: atsapbx.v1.ProvisionTenantRequest
	(*ProvisionTenantResponse)(nil),    // 7: atsapbx.v1.ProvisionTenantResponse
	(*ProvisionPrincipalRequest)(nil),  // 8: atsapbx.v1.ProvisionPrincipalRequest
	(*ProvisionPrincipalResponse)(nil), // 9: atsapbx.v1.ProvisionPrincipalResponse
	(*SetTenantStatusRequest)(nil),     // 10: atsapbx.v1.SetTenantStatusRequest
	(*SetTenantStatusResponse)(nil),    // 11: atsapbx.v1.SetTenantStatusResponse
	(*SetPrincipalStatusRequest)(nil),  // 12: atsapbx.v1.SetPrincipalStatusRequest
	(*SetPrincipalStatusResponse)(nil), // 13: atsapbx.v1.SetPrincipalStatusResponse
	(*GrantRoleRequest)(nil),           // 14: atsapbx.v1.GrantRoleRequest
	(*GrantRoleResponse)(nil),          // 15: atsapbx.v1.GrantRoleResponse
	(*IssueApiKeyRequest)(nil),         // 16: atsapbx.v1.IssueApiKeyRequest
	(*IssueApiKeyResponse)(nil),        // 17: atsapbx.v1.IssueApiKeyResponse
	(*RevokeApiKeyRequest)(nil),        // 18: atsapbx.v1.RevokeApiKeyRequest
	(*RevokeApiKeyResponse)(nil),       // 19: atsapbx.v1.RevokeApiKeyResponse
	(*AuditRecord)(nil),                // 20: atsapbx.v1.AuditRecord
	(*ListAuditRequest)(nil),           // 21: atsapbx.v1.ListAuditRequest
	(*ListAuditResponse)(nil),          // 22: atsapbx.v1.ListAuditResponse
	(*timestamppb.Timestamp)(nil),      // 23: google.protobuf.Timestamp
}
var file_atsapbx_v1_identity_proto_depIdxs = []int32{
	0,  // 0: atsapbx.v1.Tenant.status:type_name -> atsapbx.v1.TenantStatus
	23, // 1: atsapbx.v1.Tenant.created_at:type_name -> google.protobuf.Timestamp
	1,  // 2: atsapbx.v1.Principal.status:type_name -> atsapbx.v1.PrincipalStatus
	23, // 3: atsapbx.v1.Principal.created_at:type_name -> google.protobuf.Timestamp
	23, // 4: atsapbx.v1.AuthenticateUserResponse.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 5: atsapbx.v1.ProvisionTenantResponse.tenant:type_name -> atsapbx.v1.Tenant
	3,  // 6: atsapbx.v1.ProvisionPrincipalResponse.principal:type_name -> atsapbx.v1.Principal
	0,  // 7: atsapbx.v1.SetTenantStatusRequest.status:type_name -> atsapbx.v1.TenantStatus
	2,  // 8: atsapbx.v1.SetTenantStatusResponse.tenant:type_name -> atsapbx.v1.Tenant
	1,  // 9: atsapbx.v1.SetPrincipalStatusRequest.status:type_name -> atsapbx.v1.PrincipalStatus
	3,  // 10: atsapbx.v1.SetPrincipalStatusResponse.principal:type_name -> atsapbx.v1.Principal
	23, // 11: atsapbx.v1.IssueApiKeyRequest.expires_at:type_name -> google.protobuf.Timestamp
	23, // 12: atsapbx.v1.IssueApiKeyResponse.expires_at:type_name -> google.protobuf.Timestamp
	23, // 13: atsapbx.v1.AuditRecord.created_at:type_name -> google.protobuf.Timestamp
	20, // 14: atsapbx.v1.ListAuditResponse.records:type_name -> atsapbx.v1.AuditRecord
	4,  // 15: atsapbx.v1.IdentityService.AuthenticateUser:input_type -> atsapbx.v1.AuthenticateUserRequest
	6,  // 16: atsapbx.v1.IdentityService.ProvisionTenant:input_type -> atsapbx.v1.ProvisionTenantRequest
	8,  // 17: atsapbx.v1.IdentityService.ProvisionPrincipal:input_type -> atsapbx.v1.ProvisionPrincipalRequest
	10, // 18: atsapbx.v1.IdentityService.SetTenantStatus:input_type -> atsapbx.v1.SetTenantStatusRequest
	12, // 19: atsapbx.v1.IdentityService.SetPrincipalStatus:input_type -> atsapbx.v1.SetPrincipalStatusRequest
	14, // 20: atsapbx.v1.IdentityService.GrantRole:input_type -> atsapbx.v1.GrantRoleRequest
	16, // 21: atsapbx.v1.IdentityService.IssueApiKey:input_type -> atsapbx.v1.IssueApiKeyRequest
	18, // 22: atsapbx.v1.IdentityService.RevokeApiKey:input_type -> atsapbx.v1.RevokeApiKeyRequest
	21, // 23: atsapbx.v1.IdentityService.ListAudit:input_type -> atsapbx.v1.ListAuditRequest
	5,  // 24: atsapbx.v1.IdentityService.AuthenticateUser:output_type -> atsapbx.v1.AuthenticateUserResponse
	7,  // 25: atsapbx.v1.IdentityService.ProvisionTenant:output_type -> atsapbx.v1.ProvisionTenantResponse
	9,  // 26: atsapbx.v1.IdentityService.ProvisionPrincipal:output_type -> atsapbx.v1.ProvisionPrincipalResponse
	11, // 27: atsapbx.v1.IdentityService.SetTenantStatus:output_type -> atsapbx.v1.SetTenantStatusResponse
	13, // 28: atsapbx.v1.IdentityService.SetPrincipalStatus:output_type -> atsapbx.v1.SetPrincipalStatusResponse
	15, // 29: atsapbx.v1.IdentityService.GrantRole:output_type -> atsapbx.v1.GrantRoleResponse
	17, // 30: atsapbx.v1.IdentityService.IssueApiKey:output_type -> atsapbx.v1.IssueApiKeyResponse
	19, // 31: atsapbx.v1.IdentityService.RevokeApiKey:output_type -> atsapbx.v1.RevokeApiKeyResponse
	22, // 32: atsapbx.v1.IdentityService.ListAudit:output_type -> atsapbx.v1.ListAuditResponse
	24, // [24:33] is the sub-list for method output_type
	15, // [15:24] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_atsapbx_v1_identity_proto_init() }
func file_atsapbx_v1_identity_proto_init() {
	if File_atsapbx_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atsapbx_v1_identity_proto_rawDesc), len(file_atsapbx_v1_identity_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_atsapbx_v1_identity_proto_goTypes,
		DependencyIndexes: file_atsapbx_v1_identity_proto_depIdxs,
		EnumInfos:         file_atsapbx_v1_identity_proto_enumTypes,
		MessageInfos:      file_atsapbx_v1_identity_proto_msgTypes,
	}.Build()
	File_atsapbx_v1_identity_proto = out.File
	file_atsapbx_v1_identity_proto_goTypes = nil
	file_atsapbx_v1_identity_proto_depIdxs = nil
}
