// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: atsapbx/v1/pbx.proto

package atsapbxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeviceType is how a device attaches to an extension.
type DeviceType int32

const (
	DeviceType_DEVICE_TYPE_UNSPECIFIED DeviceType = 0
	DeviceType_DEVICE_TYPE_WEBRTC      DeviceType = 1
	DeviceType_DEVICE_TYPE_SIP         DeviceType = 2
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "DEVICE_TYPE_UNSPECIFIED",
		1: "DEVICE_TYPE_WEBRTC",
		2: "DEVICE_TYPE_SIP",
	}
	DeviceType_value = map[string]int32{
		"DEVICE_TYPE_UNSPECIFIED": 0,
		"DEVICE_TYPE_WEBRTC":      1,
		"DEVICE_TYPE_SIP":         2,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_atsapbx_v1_pbx_proto_enumTypes[0].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_atsapbx_v1_pbx_proto_enumTypes[0]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_atsapbx_v1_pbx_proto_rawDescGZIP(), []int{0}
}

// RegistrationStatus describes the DEVICE, not the configuration. An
// extension is configured and live from the moment it is created,
// whether or not anything has registered to it — there is no "pending"
// state, because there is nothing to apply.
type RegistrationStatus int32

const (
	RegistrationStatus_REGISTRATION_STATUS_UNSPECIFIED    RegistrationStatus = 0
	RegistrationStatus_REGISTRATION_STATUS_NOT_REGISTERED RegistrationStatus = 1
	RegistrationStatus_REGISTRATION_STATUS_REGISTERED     RegistrationStatus = 2
)

// Enum value maps for RegistrationStatus.
var (
	RegistrationStatus_name = map[int32]string{
		0: "REGISTRATION_STATUS_UNSPECIFIED",
		1: "REGISTRATION_STATUS_NOT_REGISTERED",
		2: "REGISTRATION_STATUS_REGISTERED",
	}
	RegistrationStatus_value = map[string]int32{
		"REGISTRATION_STATUS_UNSPECIFIED":    0,
		"REGISTRATION_STATUS_NOT_REGISTERED": 1,
		"REGISTRATION_STATUS_REGISTERED":     2,
	}
)

func (x RegistrationStatus) Enum() *RegistrationStatus {
	p := new(RegistrationStatus)
	*p = x
	return p
}

func (x RegistrationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegistrationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_atsapbx_v1_pbx_proto_enumTypes[1].Descriptor()
}

func (RegistrationStatus) Type() protoreflect.EnumType {
	return &file_atsapbx_v1_pbx_proto_enumTypes[1]
}

func (x RegistrationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegistrationStatus.Descriptor instead.
func (RegistrationStatus) EnumDescriptor() ([]byte, []int) {
	return file_atsapbx_v1_pbx_proto_rawDescGZIP(), []int{1}
}

// Extension is what a caller sees. It carries no credential digest and
// no engine object of any kind.
type Extension struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ExtensionId string                 `protobuf:"bytes,1,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	// Tenant-local: two tenants may each have a 1000, and they are
	// unrelated extensions with unrelated credentials.
	Number      string `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The username a device presents. Generated by the platform and
	// deliberately not derived from the number, so knowing a tenant's
	// numbering plan reveals nothing about what to authenticate as.
	AuthUsername  string             `protobuf:"bytes,4,opt,name=auth_username,json=authUsername,proto3" json:"auth_username,omitempty"`
	DeviceType    DeviceType         `protobuf:"varint,5,opt,name=device_type,json=deviceType,proto3,enum=atsapbx.v1.DeviceType" json:"device_type,omitempty"`
	Registration  RegistrationStatus `protobuf:"varint,6,opt,name=registration,proto3,enum=atsapbx.v1.RegistrationStatus" json:"registration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Extension) Reset() {
	*x = Extension{}
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Extension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extension) ProtoMessage() {}

func (x *Extension) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extension.ProtoReflect.Descriptor instead.
func (*Extension) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_pbx_proto_rawDescGZIP(), []int{0}
}

func (x *Extension) GetExtensionId() string {
	if x != nil {
		return x.ExtensionId
	}
	return ""
}

func (x *Extension) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Extension) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Extension) GetAuthUsername() string {
	if x != nil {
		return x.AuthUsername
	}
	return ""
}

func (x *Extension) GetDeviceType() DeviceType {
	if x != nil {
		return x.DeviceType
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

func (x *Extension) GetRegistration() RegistrationStatus {
	if x != nil {
		return x.Registration
	}
	return RegistrationStatus_REGISTRATION_STATUS_UNSPECIFIED
}

type CreateExtensionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	DeviceType    DeviceType             `protobuf:"varint,4,opt,name=device_type,json=deviceType,proto3,enum=atsapbx.v1.DeviceType" json:"device_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExtensionRequest) Reset() {
	*x = CreateExtensionRequest{}
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExtensionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExtensionRequest) ProtoMessage() {}

func (x *CreateExtensionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExtensionRequest.ProtoReflect.Descriptor instead.
func (*CreateExtensionRequest) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_pbx_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExtensionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateExtensionRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CreateExtensionRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateExtensionRequest) GetDeviceType() DeviceType {
	if x != nil {
		return x.DeviceType
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

type CreateExtensionResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Extension *Extension             `protobuf:"bytes,1,opt,name=extension,proto3" json:"extension,omitempty"`
	// The generated secret, returned exactly once. Never logged, never
	// audited, never retrievable by any later call.
	Secret        string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExtensionResponse) Reset() {
	*x = CreateExtensionResponse{}
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExtensionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExtensionResponse) ProtoMessage() {}

func (x *CreateExtensionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExtensionResponse.ProtoReflect.Descriptor instead.
func (*CreateExtensionResponse) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_pbx_proto_rawDescGZIP(), []int{2}
}

func (x *CreateExtensionResponse) GetExtension() *Extension {
	if x != nil {
		return x.Extension
	}
	return nil
}

func (x *CreateExtensionResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type GetExtensionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ExtensionId   string                 `protobuf:"bytes,2,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExtensionRequest) Reset() {
	*x = GetExtensionRequest{}
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExtensionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExtensionRequest) ProtoMessage() {}

func (x *GetExtensionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExtensionRequest.ProtoReflect.Descriptor instead.
func (*GetExtensionRequest) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_pbx_proto_rawDescGZIP(), []int{3}
}

func (x *GetExtensionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetExtensionRequest) GetExtensionId() string {
	if x != nil {
		return x.ExtensionId
	}
	return ""
}

type GetExtensionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Extension     *Extension             `protobuf:"bytes,1,opt,name=extension,proto3" json:"extension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExtensionResponse) Reset() {
	*x = GetExtensionResponse{}
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExtensionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExtensionResponse) ProtoMessage() {}

func (x *GetExtensionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExtensionResponse.ProtoReflect.Descriptor instead.
func (*GetExtensionResponse) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_pbx_proto_rawDescGZIP(), []int{4}
}

func (x *GetExtensionResponse) GetExtension() *Extension {
	if x != nil {
		return x.Extension
	}
	return nil
}

type ListExtensionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExtensionsRequest) Reset() {
	*x = ListExtensionsRequest{}
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExtensionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExtensionsRequest) ProtoMessage() {}

func (x *ListExtensionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExtensionsRequest.ProtoReflect.Descriptor instead.
func (*ListExtensionsRequest) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_pbx_proto_rawDescGZIP(), []int{5}
}

func (x *ListExtensionsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListExtensionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListExtensionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListExtensionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Extensions    []*Extension           `protobuf:"bytes,1,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExtensionsResponse) Reset() {
	*x = ListExtensionsResponse{}
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExtensionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExtensionsResponse) ProtoMessage() {}

func (x *ListExtensionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExtensionsResponse.ProtoReflect.Descriptor instead.
func (*ListExtensionsResponse) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_pbx_proto_rawDescGZIP(), []int{6}
}

func (x *ListExtensionsResponse) GetExtensions() []*Extension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type UpdateExtensionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ExtensionId   string                 `protobuf:"bytes,2,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	DeviceType    DeviceType             `protobuf:"varint,4,opt,name=device_type,json=deviceType,proto3,enum=atsapbx.v1.DeviceType" json:"device_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExtensionRequest) Reset() {
	*x = UpdateExtensionRequest{}
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExtensionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExtensionRequest) ProtoMessage() {}

func (x *UpdateExtensionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExtensionRequest.ProtoReflect.Descriptor instead.
func (*UpdateExtensionRequest) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_pbx_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateExtensionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateExtensionRequest) GetExtensionId() string {
	if x != nil {
		return x.ExtensionId
	}
	return ""
}

func (x *UpdateExtensionRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpdateExtensionRequest) GetDeviceType() DeviceType {
	if x != nil {
		return x.DeviceType
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

type UpdateExtensionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Extension     *Extension             `protobuf:"bytes,1,opt,name=extension,proto3" json:"extension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExtensionResponse) Reset() {
	*x = UpdateExtensionResponse{}
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExtensionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExtensionResponse) ProtoMessage() {}

func (x *UpdateExtensionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExtensionResponse.ProtoReflect.Descriptor instead.
func (*UpdateExtensionResponse) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_pbx_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateExtensionResponse) GetExtension() *Extension {
	if x != nil {
		return x.Extension
	}
	return nil
}

type DeleteExtensionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ExtensionId   string                 `protobuf:"bytes,2,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExtensionRequest) Reset() {
	*x = DeleteExtensionRequest{}
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExtensionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExtensionRequest) ProtoMessage() {}

func (x *DeleteExtensionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExtensionRequest.ProtoReflect.Descriptor instead.
func (*DeleteExtensionRequest) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_pbx_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteExtensionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteExtensionRequest) GetExtensionId() string {
	if x != nil {
		return x.ExtensionId
	}
	return ""
}

type DeleteExtensionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExtensionResponse) Reset() {
	*x = DeleteExtensionResponse{}
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExtensionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExtensionResponse) ProtoMessage() {}

func (x *DeleteExtensionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExtensionResponse.ProtoReflect.Descriptor instead.
func (*DeleteExtensionResponse) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_pbx_proto_rawDescGZIP(), []int{10}
}

type RegenerateSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ExtensionId   string                 `protobuf:"bytes,2,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateSecretRequest) Reset() {
	*x = RegenerateSecretRequest{}
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateSecretRequest) ProtoMessage() {}

func (x *RegenerateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateSecretRequest.ProtoReflect.Descriptor instead.
func (*RegenerateSecretRequest) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_pbx_proto_rawDescGZIP(), []int{11}
}

func (x *RegenerateSecretRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RegenerateSecretRequest) GetExtensionId() string {
	if x != nil {
		return x.ExtensionId
	}
	return ""
}

type RegenerateSecretResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Extension *Extension             `protobuf:"bytes,1,opt,name=extension,proto3" json:"extension,omitempty"`
	// The new secret, returned exactly once, as at creation.
	Secret        string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateSecretResponse) Reset() {
	*x = RegenerateSecretResponse{}
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateSecretResponse) ProtoMessage() {}

func (x *RegenerateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_pbx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateSecretResponse.ProtoReflect.Descriptor instead.
func (*RegenerateSecretResponse) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_pbx_proto_rawDescGZIP(), []int{12}
}

func (x *RegenerateSecretResponse) GetExtension() *Extension {
	if x != nil {
		return x.Extension
	}
	return nil
}

func (x *RegenerateSecretResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

var File_atsapbx_v1_pbx_proto protoreflect.FileDescriptor

const file_atsapbx_v1_pbx_proto_rawDesc = "" +
	"\n" +
	"\x14atsapbx/v1/pbx.proto\x12\n" +
	"atsapbx.v1\"\x8b\x02\n" +
	"\tExtension\x12!\n" +
	"\fextension_id\x18\x01 \x01(\tR\vextensionId\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12#\n" +
	"\rauth_username\x18\x04 \x01(\tR\fauthUsername\x127\n" +
	"\vdevice_type\x18\x05 \x01(\x0e2\x16.atsapbx.v1.DeviceTypeR\n" +
	"deviceType\x12B\n" +
	"\fregistration\x18\x06 \x01(\x0e2\x1e.atsapbx.v1.RegistrationStatusR\fregistration\"\xa9\x01\n" +
	"\x16CreateExtensionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x127\n" +
	"\vdevice_type\x18\x04 \x01(\x0e2\x16.atsapbx.v1.DeviceTypeR\n" +
	"deviceType\"f\n" +
	"\x17CreateExtensionResponse\x123\n" +
	"\textension\x18\x01 \x01(\v2\x15.atsapbx.v1.ExtensionR\textension\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"U\n" +
	"\x13GetExtensionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fextension_id\x18\x02 \x01(\tR\vextensionId\"K\n" +
	"\x14GetExtensionResponse\x123\n" +
	"\textension\x18\x01 \x01(\v2\x15.atsapbx.v1.ExtensionR\textension\"b\n" +
	"\x15ListExtensionsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"O\n" +
	"\x16ListExtensionsResponse\x125\n" +
	"\n" +
	"extensions\x18\x01 \x03(\v2\x15.atsapbx.v1.ExtensionR\n" +
	"extensions\"\xb4\x01\n" +
	"\x16UpdateExtensionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fextension_id\x18\x02 \x01(\tR\vextensionId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x127\n" +
	"\vdevice_type\x18\x04 \x01(\x0e2\x16.atsapbx.v1.DeviceTypeR\n" +
	"deviceType\"N\n" +
	"\x17UpdateExtensionResponse\x123\n" +
	"\textension\x18\x01 \x01(\v2\x15.atsapbx.v1.ExtensionR\textension\"X\n" +
	"\x16DeleteExtensionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fextension_id\x18\x02 \x01(\tR\vextensionId\"\x19\n" +
	"\x17DeleteExtensionResponse\"Y\n" +
	"\x17RegenerateSecretRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fextension_id\x18\x02 \x01(\tR\vextensionId\"g\n" +
	"\x18RegenerateSecretResponse\x123\n" +
	"\textension\x18\x01 \x01(\v2\x15.atsapbx.v1.ExtensionR\textension\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret*V\n" +
	"\n" +
	"DeviceType\x12\x1b\n" +
	"\x17DEVICE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12DEVICE_TYPE_WEBRTC\x10\x01\x12\x13\n" +
	"\x0fDEVICE_TYPE_SIP\x10\x02*\x85\x01\n" +
	"\x12RegistrationStatus\x12#\n" +
	"\x1fREGISTRATION_STATUS_UNSPECIFIED\x10\x00\x12&\n" +
	"\"REGISTRATION_STATUS_NOT_REGISTERED\x10\x01\x12\"\n" +
	"\x1eREGISTRATION_STATUS_REGISTERED\x10\x022\xab\x04\n" +
	"\n" +
	"PbxService\x12Z\n" +
	"\x0fCreateExtension\x12\".atsapbx.v1.CreateExtensionRequest\x1a#.atsapbx.v1.CreateExtensionResponse\x12Q\n" +
	"\fGetExtension\x12\x1f.atsapbx.v1.GetExtensionRequest\x1a .atsapbx.v1.GetExtensionResponse\x12W\n" +
	"\x0eListExtensions\x12!.atsapbx.v1.ListExtensionsRequest\x1a\".atsapbx.v1.ListExtensionsResponse\x12Z\n" +
	"\x0fUpdateExtension\x12\".atsapbx.v1.UpdateExtensionRequest\x1a#.atsapbx.v1.UpdateExtensionResponse\x12Z\n" +
	"\x0fDeleteExtension\x12\".atsapbx.v1.DeleteExtensionRequest\x1a#.atsapbx.v1.DeleteExtensionResponse\x12]\n" +
	"\x10RegenerateSecret\x12#.atsapbx.v1.RegenerateSecretRequest\x1a$.atsapbx.v1.RegenerateSecretResponseB2Z0atsap-api/internal/genproto/atsapbx/v1;atsapbxv1b\x06proto3"

var (
	file_atsapbx_v1_pbx_proto_rawDescOnce sync.Once
	file_atsapbx_v1_pbx_proto_rawDescData []byte
)

func file_atsapbx_v1_pbx_proto_rawDescGZIP() []byte {
	file_atsapbx_v1_pbx_proto_rawDescOnce.Do(func() {
		file_atsapbx_v1_pbx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atsapbx_v1_pbx_proto_rawDesc), len(file_atsapbx_v1_pbx_proto_rawDesc)))
	})
	return file_atsapbx_v1_pbx_proto_rawDescData
}

var file_atsapbx_v1_pbx_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_atsapbx_v1_pbx_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_atsapbx_v1_pbx_proto_goTypes = []any{
	(DeviceType)(0),                  // 0: atsapbx.v1.DeviceType
	(RegistrationStatus)(0),          // 1: atsapbx.v1.RegistrationStatus
	(*Extension)(nil),                // 2: atsapbx.v1.Extension
	(*CreateExtensionRequest)(nil),   // 3: atsapbx.v1.CreateExtensionRequest
	(*CreateExtensionResponse)(nil),  // 4: atsapbx.v1.CreateExtensionResponse
	(*GetExtensionRequest)(nil),      // 5: atsapbx.v1.GetExtensionRequest
	(*GetExtensionResponse)(nil),     // 6: atsapbx.v1.GetExtensionResponse
	(*ListExtensionsRequest)(nil),    // 7: atsapbx.v1.ListExtensionsRequest
	(*ListExtensionsResponse)(nil),   // 8: atsapbx.v1.ListExtensionsResponse
	(*UpdateExtensionRequest)(nil),   // 9: atsapbx.v1.UpdateExtensionRequest
	(*UpdateExtensionResponse)(nil),  // 10: atsapbx.v1.UpdateExtensionResponse
	(*DeleteExtensionRequest)(nil),   // 11: atsapbx.v1.DeleteExtensionRequest
	(*DeleteExtensionResponse)(nil),  // 12: atsapbx.v1.DeleteExtensionResponse
	(*RegenerateSecretRequest)(nil),  // 13: atsapbx.v1.RegenerateSecretRequest
	(*RegenerateSecretResponse)(nil), // 14: atsapbx.v1.RegenerateSecretResponse
}
var file_atsapbx_v1_pbx_proto_depIdxs = []int32{
	0,  // 0: atsapbx.v1.Extension.device_type:type_name -> atsapbx.v1.DeviceType
	1,  // 1: atsapbx.v1.Extension.registration:type_name -> atsapbx.v1.RegistrationStatus
	0,  // 2: atsapbx.v1.CreateExtensionRequest.device_type:type_name -> atsapbx.v1.DeviceType
	2,  // 3: atsapbx.v1.CreateExtensionResponse.extension:type_name -> atsapbx.v1.Extension
	2,  // 4: atsapbx.v1.GetExtensionResponse.extension:type_name -> atsapbx.v1.Extension
	2,  // 5: atsapbx.v1.ListExtensionsResponse.extensions:type_name -> atsapbx.v1.Extension
	0,  // 6: atsapbx.v1.UpdateExtensionRequest.device_type:type_name -> atsapbx.v1.DeviceType
	2,  // 7: atsapbx.v1.UpdateExtensionResponse.extension:type_name -> atsapbx.v1.Extension
	2,  // 8: atsapbx.v1.RegenerateSecretResponse.extension:type_name -> atsapbx.v1.Extension
	3,  // 9: atsapbx.v1.PbxService.CreateExtension:input_type -> atsapbx.v1.CreateExtensionRequest
	5,  // 10: atsapbx.v1.PbxService.GetExtension:input_type -> atsapbx.v1.GetExtensionRequest
	7,  // 11: atsapbx.v1.PbxService.ListExtensions:input_type -> atsapbx.v1.ListExtensionsRequest
	9,  // 12: atsapbx.v1.PbxService.UpdateExtension:input_type -> atsapbx.v1.UpdateExtensionRequest
	11, // 13: atsapbx.v1.PbxService.DeleteExtension:input_type -> atsapbx.v1.DeleteExtensionRequest
	13, // 14: atsapbx.v1.PbxService.RegenerateSecret:input_type -> atsapbx.v1.RegenerateSecretRequest
	4,  // 15: atsapbx.v1.PbxService.CreateExtension:output_type -> atsapbx.v1.CreateExtensionResponse
	6,  // 16: atsapbx.v1.PbxService.GetExtension:output_type -> atsapbx.v1.GetExtensionResponse
	8,  // 17: atsapbx.v1.PbxService.ListExtensions:output_type -> atsapbx.v1.ListExtensionsResponse
	10, // 18: atsapbx.v1.PbxService.UpdateExtension:output_type -> atsapbx.v1.UpdateExtensionResponse
	12, // 19: atsapbx.v1.PbxService.DeleteExtension:output_type -> atsapbx.v1.DeleteExtensionResponse
	14, // 20: atsapbx.v1.PbxService.RegenerateSecret:output_type -> atsapbx.v1.RegenerateSecretResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_atsapbx_v1_pbx_proto_init() }
func file_atsapbx_v1_pbx_proto_init() {
	if File_atsapbx_v1_pbx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atsapbx_v1_pbx_proto_rawDesc), len(file_atsapbx_v1_pbx_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_atsapbx_v1_pbx_proto_goTypes,
		DependencyIndexes: file_atsapbx_v1_pbx_proto_depIdxs,
		EnumInfos:         file_atsapbx_v1_pbx_proto_enumTypes,
		MessageInfos:      file_atsapbx_v1_pbx_proto_msgTypes,
	}.Build()
	File_atsapbx_v1_pbx_proto = out.File
	file_atsapbx_v1_pbx_proto_goTypes = nil
	file_atsapbx_v1_pbx_proto_depIdxs = nil
}
