// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: atsapbx/v1/telephony.proto

package atsapbxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCallRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// tenant_id is explicit here because no auth/identity layer exists yet
	// to derive it from a request context (LLD-02, identity, is a later
	// bounded context). Replaced by auth-derived tenant context once that
	// lands — this field is a deliberate, temporary walking-skeleton
	// scope choice, not a permanent API design.
	TenantId      string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallRequest) Reset() {
	*x = GetCallRequest{}
	mi := &file_atsapbx_v1_telephony_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallRequest) ProtoMessage() {}

func (x *GetCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_telephony_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallRequest.ProtoReflect.Descriptor instead.
func (*GetCallRequest) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_telephony_proto_rawDescGZIP(), []int{0}
}

func (x *GetCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *GetCallRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetCallResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	CallId   string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	TenantId string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// state is one of: Initiated, Screening, Routing, Presenting, Active,
	// Degraded, Terminating, Terminated (docs/telephony/domain.CallState).
	State string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	// direction is one of: INBOUND, OUTBOUND, INTERNAL.
	Direction     string         `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	SourceNumber  string         `protobuf:"bytes,5,opt,name=source_number,json=sourceNumber,proto3" json:"source_number,omitempty"`
	DestNumber    string         `protobuf:"bytes,6,opt,name=dest_number,json=destNumber,proto3" json:"dest_number,omitempty"`
	Participants  []*Participant `protobuf:"bytes,7,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallResponse) Reset() {
	*x = GetCallResponse{}
	mi := &file_atsapbx_v1_telephony_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallResponse) ProtoMessage() {}

func (x *GetCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_telephony_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallResponse.ProtoReflect.Descriptor instead.
func (*GetCallResponse) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_telephony_proto_rawDescGZIP(), []int{1}
}

func (x *GetCallResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *GetCallResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetCallResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetCallResponse) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *GetCallResponse) GetSourceNumber() string {
	if x != nil {
		return x.SourceNumber
	}
	return ""
}

func (x *GetCallResponse) GetDestNumber() string {
	if x != nil {
		return x.DestNumber
	}
	return ""
}

func (x *GetCallResponse) GetParticipants() []*Participant {
	if x != nil {
		return x.Participants
	}
	return nil
}

type Participant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParticipantId string                 `protobuf:"bytes,1,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	// role is one of: CALLER, AGENT, IVR, QUEUE, SUPERVISOR, SPECIALIST, AI.
	Role        string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	EndpointUri string `protobuf:"bytes,3,opt,name=endpoint_uri,json=endpointUri,proto3" json:"endpoint_uri,omitempty"`
	// state is one of: Invited, Ringing, Connected, OnHold, Transferring,
	// Disconnected.
	State           string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	BillableSeconds int32  `protobuf:"varint,5,opt,name=billable_seconds,json=billableSeconds,proto3" json:"billable_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Participant) Reset() {
	*x = Participant{}
	mi := &file_atsapbx_v1_telephony_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Participant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participant) ProtoMessage() {}

func (x *Participant) ProtoReflect() protoreflect.Message {
	mi := &file_atsapbx_v1_telephony_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Participant.ProtoReflect.Descriptor instead.
func (*Participant) Descriptor() ([]byte, []int) {
	return file_atsapbx_v1_telephony_proto_rawDescGZIP(), []int{2}
}

func (x *Participant) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *Participant) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Participant) GetEndpointUri() string {
	if x != nil {
		return x.EndpointUri
	}
	return ""
}

func (x *Participant) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Participant) GetBillableSeconds() int32 {
	if x != nil {
		return x.BillableSeconds
	}
	return 0
}

var File_atsapbx_v1_telephony_proto protoreflect.FileDescriptor

const file_atsapbx_v1_telephony_proto_rawDesc = "" +
	"\n" +
	"\x1aatsapbx/v1/telephony.proto\x12\n" +
	"atsapbx.v1\"F\n" +
	"\x0eGetCallRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"\xfe\x01\n" +
	"\x0fGetCallResponse\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12#\n" +
	"\rsource_number\x18\x05 \x01(\tR\fsourceNumber\x12\x1f\n" +
	"\vdest_number\x18\x06 \x01(\tR\n" +
	"destNumber\x12;\n" +
	"\fparticipants\x18\a \x03(\v2\x17.atsapbx.v1.ParticipantR\fparticipants\"\xac\x01\n" +
	"\vParticipant\x12%\n" +
	"\x0eparticipant_id\x18\x01 \x01(\tR\rparticipantId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12!\n" +
	"\fendpoint_uri\x18\x03 \x01(\tR\vendpointUri\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12)\n" +
	"\x10billable_seconds\x18\x05 \x01(\x05R\x0fbillableSeconds2V\n" +
	"\x10TelephonyService\x12B\n" +
	"\aGetCall\x12\x1a.atsapbx.v1.GetCallRequest\x1a\x1b.atsapbx.v1.GetCallResponseB2Z0atsap-api/internal/genproto/atsapbx/v1;atsapbxv1b\x06proto3"

var (
	file_atsapbx_v1_telephony_proto_rawDescOnce sync.Once
	file_atsapbx_v1_telephony_proto_rawDescData []byte
)

func file_atsapbx_v1_telephony_proto_rawDescGZIP() []byte {
	file_atsapbx_v1_telephony_proto_rawDescOnce.Do(func() {
		file_atsapbx_v1_telephony_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atsapbx_v1_telephony_proto_rawDesc), len(file_atsapbx_v1_telephony_proto_rawDesc)))
	})
	return file_atsapbx_v1_telephony_proto_rawDescData
}

var file_atsapbx_v1_telephony_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_atsapbx_v1_telephony_proto_goTypes = []any{
	(*GetCallRequest)(nil),  // 0: atsapbx.v1.GetCallRequest
	(*GetCallResponse)(nil), // 1: atsapbx.v1.GetCallResponse
	(*Participant)(nil),     // 2: atsapbx.v1.Participant
}
var file_atsapbx_v1_telephony_proto_depIdxs = []int32{
	2, // 0: atsapbx.v1.GetCallResponse.participants:type_name -> atsapbx.v1.Participant
	0, // 1: atsapbx.v1.TelephonyService.GetCall:input_type -> atsapbx.v1.GetCallRequest
	1, // 2: atsapbx.v1.TelephonyService.GetCall:output_type -> atsapbx.v1.GetCallResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_atsapbx_v1_telephony_proto_init() }
func file_atsapbx_v1_telephony_proto_init() {
	if File_atsapbx_v1_telephony_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atsapbx_v1_telephony_proto_rawDesc), len(file_atsapbx_v1_telephony_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_atsapbx_v1_telephony_proto_goTypes,
		DependencyIndexes: file_atsapbx_v1_telephony_proto_depIdxs,
		MessageInfos:      file_atsapbx_v1_telephony_proto_msgTypes,
	}.Build()
	File_atsapbx_v1_telephony_proto = out.File
	file_atsapbx_v1_telephony_proto_goTypes = nil
	file_atsapbx_v1_telephony_proto_depIdxs = nil
}
