# syntax=docker/dockerfile:1

FROM golang:1.25-bookworm AS build
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd
COPY internal ./internal

RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/sip-ua ./cmd/sip-ua

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/sip-ua /usr/local/bin/sip-ua

USER nonroot:nonroot
ENTRYPOINT ["/usr/local/bin/sip-ua"]
